# Canvas instance URL. Usually you just need to replace "canvas" with your Canvas instance name.
canvas_url: https://canvas.instructure.com

# The endpoint for the ClickUp API, rarely changed.
clickup_url: https://api.clickup.com/api/v2

# Token for Canvas, this is found on your settings page
canvas_token: <YOUR_TOKEN_HERE>

# Token for ClickUp, this is found in Settings > Apps
clickup_token: <YOUR_TOKEN_HERE>

# ClickUp List ID
clickup_list_id: 163143838

# Data to sync
# Enabled determines if the data should be synced at all.
# Overwrite means that any data from Canvas will overwrite data in ClickUp.
# Disabling disables both creating and updating.
sync:
  # Assignment title. Must be enabled.
  title:
    overwrite: true
  # The assignment description.
  description:
    enabled: true
    overwrite: true
  # The assignment due date. Not all assignments have due dates.
  due_at:
    enabled: true
    overwrite: true
  # When the assignment is unlocked. Not all assignments may have this!
  start_at:
    enabled: true
    overwrite: true
  # The assignment status. Whether "To-Do", "Submitted", or "Graded"
  status:
    enabled: true
    # You can ignore status overwriting by adding a label called "Ignored" to the ClickUp task.
    overwrite: true
  # The course name custom field. No overwrite needed, since assignments can't be moved.
  course_name:
    enabled: true

# Other options on what to sync
options:
  # Whether to sync assignments that have no way of being submitted.
  # Typically these are assignments reserved for grading purposes.
  # They likely have a grade, but no way to submit.
  sync_submissionless_assignments: true
  # Whether to skip syncing assignments if a proper dropdown option cannot be found.
  # This can be used to skip some courses, if desired.
  # If left false, the program will die until you add the proper option.
  skip_missing_dropdown_options: false